### ISSUE TITLE
create social media component

### ISSUE THREAD

**Issue by emirulucay** [productdevbookcom/productdevbookcom#9]
![image](https://github.com/productdevbookcom/productdevbookcom/assets/74816727/ebbda98f-d944-4433-9d90-2b5cbb9435b5)

**Comment by productdevbook** [comment]
https://github.com/egoist/tailwindcss-icons

**Comment by productdevbook** [comment]
Name: Iconify IntelliSense
Id: antfu.iconify
Description: Intelligent Iconify previewing and searching for VS Code
Version: 0.5.4
Publisher: Anthony Fu
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=antfu.iconify
